export interface Announcement {
    id?: number;
    uuid?: string;
    title: string;
    message: string;
    shortMessage?: string;
    type: 'info' | 'success' | 'warning' | 'error' | 'emergency' | 'maintenance' | 'holiday' | 'event' | 'update' | 'system';
    priority: 'low' | 'medium' | 'high' | 'critical';
    isActive: boolean;
    isPopup: boolean;
    scrollSpeed: number;
    textColor: string;
    backgroundColor: string;
    borderColor: string;
    iconName?: string;
    showIcon: boolean;
    showCloseButton: boolean;
    pauseOnHover: boolean;
    repeatLoop: boolean;
    animationType: string;
    clickableLink?: string;
    openInNewTab: boolean;
    startTime: string | Date;
    endTime: string | Date;
    displayOrder: number;
    targetRoles: string;
    targetPages: string;
    deviceVisibility: 'all' | 'desktop' | 'mobile';
    viewCount?: number;
    clickCount?: number;
}
