export interface Issue {
  issueId: number;
  bookId: string;
  memberId: string;
  bookTitle: string;
  memberName: string;
  memberEmail?: string;
  memberPhone?: string;
  memberDept?: string;
  memberCourse?: string;
  membershipType?: string;
  memberPhoto?: string;
  academicSession?: string;
  guardianName?: string;
  guardianPhone?: string;
  bookPrice?: number;
  isbn?: string;
  bookAuthor?: string;
  bookStream?: string;
  bookPublisher?: string;
  publicationYear?: number;
  publisher?: string;
  shelfLocation?: string;
  issueDate: string;
  dueDate: string;
  returnDate?: string;
  status: 'issued' | 'returned' | 'lost';
  fineAmount: number;
  finePaid: number;
  createdAt?: string;
  dynamicFine?: number;
}
